version: '3'
services:
  db:
    restart: always
    image: postgres:10.3
    environment:
      - POSTGRES_USER=govoteuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=GoVoteGSO
    ports:
      - 9001:5432
  govote:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - DB_HOST=db
      - DB_NAME=GoVoteGSO
      - DB_USER=govoteuser
      - DB_PASS=password
      - DB_PORT=5432
      - DB_TABLE=guilfordvoters
      - NODE_ENV=development